### ISSUE TITLE
Conversion to LLFF example?

### ISSUE THREAD

**Issue by henrypearce4D** [Fraunhofer-IIS/camorph#21]
Hi do you have a example of conversion to LLFF ?

I tested Colmap to LLFF but thats missing  properties: "near_far_bounds"

I'm wondering what format should work?

**Comment by bbrand-iis** [comment]
Hey henrypearce4D,

LLFF is a format where near and far bounds are required. Currently, no other formats including Colmap support this attribute, because it is irrelevant in most cases. To convert colmap to llff, you need to supply near and far bounds via the config.json that should automatically be generated in your destination folder. You can [refer to the documentation for a guide on how to set crucial properties](https://github.com/Fraunhofer-IIS/camorph/blob/main/docs/sphinx/crucial_properties.md). Usually, you can set it to some dummy value as 0.01 and 1000. To be more accurate, you would need to have some understanding of your scene and where the region of interest is.

**Comment by henrypearce4D** [comment]
Hi that's great info thankyou, I now have an .npy!
